#!/usr/bin/env bash
# open teams

# keyed to super-1
set -e

# if python-fire window is open, switch to it
# https://superuser.com/questions/142945/bash-command-to-focus-a-specific-window
wmctrl -a "Microsoft Teams" && true
RC=$?

# https://stackoverflow.com/questions/26675681/how-to-check-the-exit-status-using-an-if-statement
if [[ "${RC}" == 1 ]]; then
    echo "starting teams"
    google-chrome https://teams.microsoft.com
fi

