---
#https://docs.ansible.com/ansible/latest/collections/ansible/builtin/blockinfile_module.html

- name: Insert/Update configuration using a local file and validate it
  blockinfile:
    block: "{{ lookup('file', './pinephone.conf') }}"
    path: /etc/ssh/sshd_config
    backup: yes
    validate: /usr/sbin/sshd -T -f %s

#- name: add desktop launcher
 

#https://serverfault.com/questions/840156/create-non-root-user-and-disable-root-ssh-in-ansible
# key should have been put in place by script run on phone
- name: put ssh key in place
  authorized_key:
    user: poleguy
    key: "{{ lookup('file', '~/.ssh/pinephone_id_ed25519.pub') }}"
    exclusive: no

