---
#https://docs.ansible.com/ansible/latest/collections/ansible/builtin/blockinfile_module.html

# https://wiki.mobian-project.org/doku.php?id=install
- name: install sshd
  package:
    name: openssh-server

- name: clean duplicates
  replace:
    path: '/etc/ssh/sshd_config'
    after: 'PasswordAuthentication'
    regexp: '^(.*)PasswordAuthentication(.*)$'
    replace: ''
- name: clean duplicates
  replace:
    path: '/etc/ssh/sshd_config'
    after: 'PermitEmptyPasswords'
    regexp: '^(.*)PermitEmptyPasswords(.*)$'
    replace: ''
- name: clean duplicates
  replace:
    path: '/etc/ssh/sshd_config'
    after: 'PermitRootLogin'
    regexp: '^(.*)PermitRootLogin(.*)$'
    replace: ''


#https://stackoverflow.com/questions/65228192/ansible-disable-ssh-password-authentication
- name: set password login no
  lineinfile:
    path: '/etc/ssh/sshd_config'
    regexp: '^(.*)PasswordAuthentication(.*)$'
    line: 'PasswordAuthentication no'
  notify: restart sshd

- name: Disable empty password login
  lineinfile:
    path: '/etc/ssh/sshd_config'
    regexp: '^(.*)PermitEmptyPasswords(.*)$'
    line: 'PermitEmptyPasswords no'
  notify: restart sshd

- name: Disable remote root login
  lineinfile:
    path: '/etc/ssh/sshd_config'
    regexp: '^(.*)PermitRootLogin(.*)$'
    line: 'PermitRootLogin no'
  notify: restart sshd

#- name: add desktop launcher

#https://github.com/vitalk/ansible-secure-ssh/blob/master/tasks/main.yml


- name: enable sshd
  service: 
    name: sshd 
    enabled: yes

- name: start sshd
  service: 
    name: sshd 
    state: started


  
# #https://stackoverflow.com/questions/25505146/how-to-copy-files-between-two-nodes-using-ansible
# # using rsync_path to avoid using sudo
# - name: put poleguy key on phone
#   synchronize:
#     mode: pull
#     src: rsync://dualie.poleguy.com/home/poleguy/.ssh/id_ed25519.pub
#     dest: /home/mobian/.ssh/dualie_id_ed25519.pub
# #    rsync_path: rsync
# #  delegate_to: dualie
#   become: no

# too much magic in synchronize
#https://github.com/ansible/ansible/issues/5702

- name: put poleguy key on phone
  command: rsync poleguy@dualie.poleguy.com:/home/poleguy/.ssh/id_ed25519.pub /home/mobian/.ssh/dualie_id_ed25519.pub
#  delegate_to: localhost    
        
#https://serverfault.com/questions/840156/create-non-root-user-and-disable-root-ssh-in-ansible
- name: Add authorized key
  authorized_key:
    user: mobian
    key: "{{ lookup('file', '~/.ssh/dualie_id_ed25519.pub') }}"
    exclusive: no
  

# scp -P 22 ~/.ssh/id_ed25519.pub poleguy@dualie.poleguy.com:/home/poleguy/.ssh/pinephone_id_ed25519.pub 
