#!/usr/bin/env bash


# check if this was called by source to prevent incorrect usage
(return 0 2>/dev/null) && sourced=1 || sourced=0

if [ $sourced -eq 0 ]; then
    echo "You must source this script. Do not run it directly."
    exit 1    
fi

# https://unix.stackexchange.com/questions/383541/how-to-save-restore-all-shell-options-including-errexit
# the virtualenvwrapper.sh scripts don't do happy things with set -euo pipefail
# space before to prevent them from ending on the command line
OLDOPTS="$(set +o | sed -e 's/^/ /')"
case $- in
  *e*) OLDOPTS="$OLDOPTS; set -e";;
  *) OLDOPTS="$OLDOPTS; set +e";;
esac
set +eu

# https://unix.stackexchange.com/questions/162165/check-that-a-bash-script-has-exactly-two-arguments-which-are-directories
REPONAME=$(pwd | sed -e 's|^/||' -e 's|/|__|g') #make a unique virtualenv based off the current path

source virtualenvwrapper.sh || true

echo "virtualenvwrapper.sh complete"
# deactivate sometimes finds the conda version
deactivate

rmvirtualenv $REPONAME

#restore settings
eval "${OLDOPTS}"
