---
#https://docs.ansible.com/ansible/latest/collections/ansible/builtin/blockinfile_module.html

- name: Insert/Update configuration using a local file and validate it
  blockinfile:
    block: "{{ lookup('file', './pinephone.conf') }}"
    path: /etc/ssh/sshd_config
    backup: yes
    validate: /usr/sbin/sshd -T -f %s